# -*- coding: utf-8 -*-
"""regex.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rxUeTcXdyv7fiS5TKFY3SRy6ic017WS_
"""

import re

test = 'Best python course'
re.match('Best', test)
# re.match('Best|Good', test)

test2 = 'Best python course'
# re.match('Best|Good', test2)

test3 = 'Good Best python course'
# re.search('Best|Good', test3)
re.findall('Best|Good', test3)
re.findall('AAAA', test3)